show databases;

create database db_PORTIFOLIO;

USE db_PORTIFOLIO;

SHOW tables;

CREATE TABLE TBL_ALUNO ( 
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(15) UNIQUE NOT NULL,
MATRICULA VARCHAR(40) UNIQUE NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20),
UNIQUE INDEX(ID) 
);

CREATE TABLE TBL_CURSO (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME_CURSO VARCHAR(40)NOT NULL,
CARGA_HORARIA INT NOT NULL,
UNIQUE INDEX(ID)
);

CREATE TABLE TBL_TURMA (
ID INT PRIMARY KEY AUTO_INCREMENT,
SEMESTRE VARCHAR(20) NOT NULL,
UNIQUE INDEX(ID)
);

CREATE TABLE TBL_DISCIPLINA (
ID_DISCIPLINA INT PRIMARY KEY AUTO_INCREMENT,
NOME_DISCIPLINA VARCHAR(100) NOT NULL,
CARGA_HORARIA INT NOT NULL,
UNIQUE INDEX(ID_DISCIPLINA)
);

CREATE TABLE TBL_PROFESSOR (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
ESPECIALIZACAO VARCHAR(100),
ID_DISCIPLINA INT NOT NULL,
CONSTRAINT FK_PROFESSOR_DISCIPLINA
FOREIGN KEY (ID_DISCIPLINA)
REFERENCES TBL_DISCIPLINA(ID_DISCIPLINA),
UNIQUE INDEX(ID)
);

CREATE TABLE TBL_ALUNO_TURMA (
ID INT PRIMARY KEY AUTO_INCREMENT,
ANO_SEMESTRE VARCHAR(20) NOT NULL,
ID_ALUNO INT NOT NULL,
ID_TURMA INT NOT NULL,
FOREIGN KEY (ID_ALUNO)
REFERENCES TBL_ALUNO(ID),
FOREIGN KEY (ID_TURMA)
REFERENCES TBL_TURMA(ID),
UNIQUE INDEX(ID)
);

CREATE TABLE TBL_CURSO_DISCIPLINA (
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_CURSO INT NOT NULL,
ID_DISCIPLINA INT NOT NULL,
FOREIGN KEY (ID_CURSO)
REFERENCES TBL_CURSO(ID),
FOREIGN KEY (ID_DISCIPLINA)
REFERENCES TBL_DISCIPLINA(ID_DISCIPLINA),
UNIQUE INDEX(ID)
);

CREATE TABLE TBL_NOTA_ALUNO_DISCIPLINA (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOTA DECIMAL(5, 2) NOT NULL, DATA DATE NOT NULL,
ID_ALUNO INT NOT NULL,
ID_DISCIPLINA INT NOT NULL,
FOREIGN KEY (ID_ALUNO)
REFERENCES TBL_ALUNO(ID),
FOREIGN KEY (ID_DISCIPLINA)
REFERENCES TBL_DISCIPLINA(ID_DISCIPLINA),
UNIQUE INDEX(ID)
);
